name: bloc_lint
description: Lint rules for BLoC library.
version: 0.0.0
environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0

dev_dependencies:
  very_good_analysis: ^6.0.0
  flutter_bloc: ^8.1.6
  test: ^1.25.8
